/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIQytetet;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import modeloqytetet.Jugador;
import modeloqytetet.MetodoSalirCarcel;
import modeloqytetet.Qytetet;
import modeloqytetet.TipoCasilla;
import org.omg.PortableInterceptor.SYSTEM_EXCEPTION;


/**
 *
 * @author Lorena
 */
public class ControladorQytetet extends javax.swing.JFrame {
   Qytetet modeloQytetet = Qytetet.getInstance();
    
    /**
     * Creates new form ControladorQytetet
     */
    public ControladorQytetet() {
        initComponents();
        
        
        this.comprarPropiedad.setEnabled(false);
        this.aplicarSorpresa.setEnabled(false);
        this.salirDado.setEnabled(false);
        this.salirPagando.setEnabled(false);
        this.siguienteJugador.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vistaQytetet2 = new GUIQytetet.VistaQytetet();
        salirPagando = new javax.swing.JButton();
        salirDado = new javax.swing.JButton();
        jugar = new javax.swing.JButton();
        comprarPropiedad = new javax.swing.JButton();
        siguienteJugador = new javax.swing.JButton();
        aplicarSorpresa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        salirPagando.setText("Salir Carcel Pagando");
        salirPagando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirPagandoActionPerformed(evt);
            }
        });

        salirDado.setText("Salir Carcel Dado");
        salirDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirDadoActionPerformed(evt);
            }
        });

        jugar.setText("Jugar");
        jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarActionPerformed(evt);
            }
        });

        comprarPropiedad.setText("Comprar Propiedad");
        comprarPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarPropiedadActionPerformed(evt);
            }
        });

        siguienteJugador.setText("Siguiente Jugador");
        siguienteJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteJugadorActionPerformed(evt);
            }
        });

        aplicarSorpresa.setText("Aplicar Sorpresa");
        aplicarSorpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicarSorpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(vistaQytetet2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(salirPagando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salirDado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jugar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comprarPropiedad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aplicarSorpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(siguienteJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(vistaQytetet2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(salirPagando)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salirDado)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(jugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comprarPropiedad)
                            .addComponent(aplicarSorpresa)))
                    .addComponent(siguienteJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirPagandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirPagandoActionPerformed
        boolean resultado = modeloQytetet.intentarSalirCarcel(MetodoSalirCarcel.PAGANDOLIBERTAD);
        this.salirPagando.setEnabled(false);
        this.salirDado.setEnabled(false);
        if(resultado){
            JOptionPane.showMessageDialog(this, "Sales de la cárcel");
            this.jugar.setEnabled(true);
        }else {
            JOptionPane.showMessageDialog(this, "NO sales de la carcel");
            this.siguienteJugador.setEnabled(true);
        }
        this.vistaQytetet2.actualizar(modeloQytetet);
    }//GEN-LAST:event_salirPagandoActionPerformed

    private void salirDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirDadoActionPerformed
        boolean resultado = modeloQytetet.intentarSalirCarcel(MetodoSalirCarcel.TIRANDODADO);
        this.salirPagando.setEnabled(false);
        this.salirDado.setEnabled(false);
        if(resultado){
            JOptionPane.showMessageDialog(this, "Sales de la cárcel");
            this.jugar.setEnabled(true);
        }else {
            JOptionPane.showMessageDialog(this, "NO sales de la carcel");
            this.siguienteJugador.setEnabled(true);
        }
        this.vistaQytetet2.actualizar(modeloQytetet);
    }//GEN-LAST:event_salirDadoActionPerformed

    private void jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarActionPerformed
        boolean propiTengo = modeloQytetet.jugar();
        this.jugar.setEnabled(false);
        
        TipoCasilla casilla = modeloQytetet.getJugadorActual().getCasillaActual().getTipo();
        
        //Comprobamos que tipo de casilla es
            if(casilla == TipoCasilla.CALLE){
                vistaQytetet2.actualizar(modeloQytetet);
                if(!propiTengo){
                    this.comprarPropiedad.setEnabled(true);
                    this.siguienteJugador.setEnabled(true);

                }else{
                    this.siguienteJugador.setEnabled(true);
                    
                }
            }else if(casilla == TipoCasilla.SORPRESA){
                vistaQytetet2.actualizar(modeloQytetet);
                this.aplicarSorpresa.setEnabled(true);
            }else if(casilla == TipoCasilla.CARCEL){
                vistaQytetet2.actualizar(modeloQytetet);
                this.salirDado.setEnabled(true);
                this.salirPagando.setEnabled(true);
            }else if(casilla == TipoCasilla.IMPUESTO){
                vistaQytetet2.actualizar(modeloQytetet);
                this.siguienteJugador.setEnabled(true);

            }else if(casilla == TipoCasilla.PARKING){
                vistaQytetet2.actualizar(modeloQytetet);
                this.siguienteJugador.setEnabled(true);

            }else if(casilla == TipoCasilla.JUEZ){
                vistaQytetet2.actualizar(modeloQytetet);

            }else if(casilla == TipoCasilla.SALIDA){
                vistaQytetet2.actualizar(modeloQytetet);
                this.siguienteJugador.setEnabled(true);

            }
        
    }//GEN-LAST:event_jugarActionPerformed

    private void comprarPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarPropiedadActionPerformed
        boolean puedoComprar = modeloQytetet.comprarTituloPropiedad();
        VistaCasilla casilla = new VistaCasilla();
        if(puedoComprar){
            vistaQytetet2.actualizar(modeloQytetet);
            casilla.actualizar("Enhorabuena!! Has podido comprar la propiedad");            
        }
        else{
            vistaQytetet2.actualizar(modeloQytetet);
            casilla.actualizar("Ohhhh!! No has podido comprar la propiedad");            
        }
        this.comprarPropiedad.setEnabled(false);
        this.siguienteJugador.setEnabled(true);

    }//GEN-LAST:event_comprarPropiedadActionPerformed

    private void aplicarSorpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicarSorpresaActionPerformed
        boolean puedoApliSorpresa = modeloQytetet.aplicarSorpresa();
        VistaCasilla casilla = new VistaCasilla();
        if(puedoApliSorpresa){
            vistaQytetet2.actualizar(modeloQytetet);
            casilla.actualizar("Enhorabuena!! Has podido aplicar la sorpresa");            
        }
        else{
            vistaQytetet2.actualizar(modeloQytetet);
            casilla.actualizar("Ohhhh!! No has podido aplicar la sorpresa");            
        }
        this.aplicarSorpresa.setEnabled(false);
        this.siguienteJugador.setEnabled(true);
    }//GEN-LAST:event_aplicarSorpresaActionPerformed

    private void siguienteJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteJugadorActionPerformed
        // TODO add your handling code here:
        modeloQytetet.siguienteJugador();
        vistaQytetet2.actualizar(modeloQytetet);
        this.habilitarComenzarTurno();
    }//GEN-LAST:event_siguienteJugadorActionPerformed

    public void habilitarComenzarTurno(){
        this.comprarPropiedad.setEnabled(false);
        this.siguienteJugador.setEnabled(false);
        this.aplicarSorpresa.setEnabled(false);
        if(modeloQytetet.getJugadorActual().getEncarcelado()){
            this.salirPagando.setEnabled(true);
            this.salirDado.setEnabled(true);
        }
        else
            this.jugar.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        ControladorQytetet controladorQytetet= new ControladorQytetet();
        CapturaNombreJugadores capturaNombres = new CapturaNombreJugadores(controladorQytetet, true);
        ArrayList<String> nombres = capturaNombres.obtenerNombres();
        Qytetet juego = Qytetet.getInstance();
        juego.inicializarJuego(nombres);
        Dado.createInstance(controladorQytetet);
        vistaQytetet2.actualizar(juego);
        
        
        
        
        controladorQytetet.setVisible(true);
    }

    public void actualizar(Qytetet modeloQytetet){
        VistaQytetet bancarrota = new VistaQytetet();
        this.habilitarComenzarTurno();
        vistaQytetet2.actualizar(modeloQytetet);
        if(bancarrota.bancarrota(modeloQytetet)){
            JOptionPane.showMessageDialog(this, modeloQytetet.obtenerRanking());
            
        }
        
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aplicarSorpresa;
    private javax.swing.JButton comprarPropiedad;
    private javax.swing.JButton jugar;
    private javax.swing.JButton salirDado;
    private javax.swing.JButton salirPagando;
    private javax.swing.JButton siguienteJugador;
    private static GUIQytetet.VistaQytetet vistaQytetet2;
    // End of variables declaration//GEN-END:variables
}
